final url = 'http://192.168.143.142:3000/';
final registrationApi = url + "registerUser" ;
final communityAddApi = url + "community/add" ;
final postAddApi=url+"post/addPost";
final findUser = url + 'findUser';
final getUsers = url + "getUsers";
final updateChats = url + "addChat";
final fetchPostApi= url+"post/getUserPosts";
final communityGetApi = url + 'community/get';
